# Generated by Django 5.0.6 on 2024-05-17 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tassessmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('course', models.CharField(choices=[('--Select--', '--Select--'), ('Option1', 'Option1')], max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('entry_scheme', models.CharField(choices=[('--Select--', '--Select--'), ('Option1', 'Option1')], max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('intake', models.CharField(choices=[('--Select--', '--Select--'), ('Option1', 'Option1')], max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sponsorship', models.CharField(choices=[('--Select--', '--Select--'), ('Option1', 'Option1')], max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('date_of_birth', models.DateField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('residence', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
